@ECHO OFF
REM Insert your files in "archives" directory

REM delete all mapped connections
NET USE * /delete /y

REM Create a log directory format DD-MM-YY.
MKDIR C:\transferfiles\logs\%DATE:~0,2%"-"%DATE:~3,2%"-"%DATE:~8,2%

START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd 1"IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"
TIMEOUT 90
START Parameters.cmd "IP_ADDRESS" "CLIENT_NAME"

...

EXIT